"""add tables and static data

Revision ID: a0fc8268b2bb
Revises:
Create Date: 2023-08-17 15:41:08.069006

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a0fc8268b2bb"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # TABLE: fell
    fell = op.create_table(
        "fell",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.Enum(
                "ALLEN_CRAGS",
                "ANGLETARN_PIKES",
                "ARD_CRAGS",
                "ARMBOTH_FELL",
                "ARNISON_CRAG",
                "ARTHURS_PIKE",
                "BAKESTALL",
                "BANNERDALE_CRAGS",
                "BARF",
                "BARROW",
                "BASE_BROWN",
                "BEDA_FELL",
                "BINSEY",
                "BIRKHOUSE_MOOR",
                "BIRKS",
                "BLACK_FELL",
                "BLAKE_FELL",
                "BLEA_RIGG",
                "BLEABERRY_FELL",
                "BLENCATHRA",
                "BONSCALE_PIKE",
                "BOWFELL",
                "BOWSCALE_FELL",
                "BRAE_FELL",
                "BRANDRETH",
                "BRANSTREE",
                "BRIM_FELL",
                "BROCK_CRAGS",
                "BROOM_FELL",
                "BUCKBARROW",
                "BURNBANK_FELL",
                "CALF_CRAG",
                "CARL_SIDE",
                "CARROCK_FELL",
                "CASTLE_CRAG",
                "CATBELLS",
                "CATSTYE_CAM",
                "CAUSEY_PIKE",
                "CAW_FELL",
                "CLOUGH_HEAD",
                "COLD_PIKE",
                "CONISTON_OLD_MAN",
                "CRAG_FELL",
                "CRINKLE_CRAGS",
                "DALE_HEAD",
                "DODD",
                "DOLLYWAGGON_PIKE",
                "DOVE_CRAG",
                "DOW_CRAG",
                "EAGLE_CRAG",
                "EEL_CRAG",
                "ESK_PIKE",
                "FAIRFIELD",
                "FELLBARROW",
                "FLEETWITH_PIKE",
                "FROSWICK",
                "GAVEL_FELL",
                "GIBSON_KNOTT",
                "GLARAMARA",
                "GLENRIDDING_DODD",
                "GOWBARROW_FELL",
                "GRANGE_FELL",
                "GRASMOOR",
                "GRAY_CRAG",
                "GRAYSTONES",
                "GREAT_BORNE",
                "GREAT_CALVA",
                "GREAT_CARRS",
                "GREAT_COCKUP",
                "GREAT_CRAG",
                "GREAT_DODD",
                "GREAT_END",
                "GREAT_GABLE",
                "GREAT_MELL_FELL",
                "GREAT_RIGG",
                "GREAT_SCA_FELL",
                "GREEN_CRAG",
                "GREEN_GABLE",
                "GREY_CRAG",
                "GREY_FRIAR",
                "GREY_KNOTTS",
                "GRIKE",
                "GRISEDALE_PIKE",
                "HALLIN_FELL",
                "HARD_KNOTT",
                "HARRISON_STICKLE",
                "HART_CRAG",
                "HART_SIDE",
                "HARTER_FELL_ESKDALE",
                "HARTER_FELL_MARDALE",
                "HARTSOP_ABOVE_HOW",
                "HARTSOP_DODD",
                "HAYCOCK",
                "HAYSTACKS",
                "HELM_CRAG",
                "HELVELLYN",
                "HEN_COMB",
                "HERON_PIKE",
                "HIGH_CRAG",
                "HIGH_HARTSOP_DODD",
                "HIGH_PIKE_CALDBECK",
                "HIGH_PIKE_SCANDALE",
                "HIGH_RAISE_HIGH_STREET",
                "HIGH_RAISE_LANGDALE",
                "HIGH_RIGG",
                "HIGH_SEAT",
                "HIGH_SPY",
                "HIGH_STILE",
                "HIGH_STREET",
                "HIGH_TOVE",
                "HINDSCARTH",
                "HOLME_FELL",
                "HOPEGILL_HEAD",
                "ILL_BELL",
                "ILLGILL_HEAD",
                "KENTMERE_PIKE",
                "KIDSTY_PIKE",
                "KIRK_FELL",
                "KNOTT",
                "KNOTT_RIGG",
                "LANK_RIGG",
                "LATRIGG",
                "LING_FELL",
                "LINGMELL",
                "LINGMOOR_FELL",
                "LITTLE_HART_CRAG",
                "LITTLE_MELL_FELL",
                "LOADPOT_HILL",
                "LOFT_CRAG",
                "LONG_SIDE",
                "LONGLANDS_FELL",
                "LONSCALE_FELL",
                "LORDS_SEAT",
                "LOUGHRIGG_FELL",
                "LOW_FELL",
                "LOW_PIKE",
                "MAIDEN_MOOR",
                "MARDALE_ILL_BELL",
                "MEAL_FELL",
                "MELLBREAK",
                "MIDDLE_DODD",
                "MIDDLE_FELL",
                "MUNGRISDALE_COMMON",
                "NAB_SCAR",
                "NETHERMOST_PIKE",
                "OUTERSIDE",
                "PAVEY_ARK",
                "PIKE_OF_BLISCO",
                "PIKE_OF_STICKLE",
                "PILLAR",
                "PLACE_FELL",
                "RAISE",
                "RAMPSGILL_HEAD",
                "RANNERDALE_KNOTTS",
                "RAVEN_CRAG",
                "RED_PIKE_BUTTERMERE",
                "RED_PIKE_WASDALE",
                "RED_SCREES",
                "REST_DODD",
                "ROBINSON",
                "ROSSETT_PIKE",
                "ROSTHWAITE_FELL",
                "SAIL",
                "SALE_FELL",
                "SALLOWS",
                "SCAFELL",
                "SCAFELL_PIKE",
                "SCAR_CRAGS",
                "SCOAT_FELL",
                "SEAT_SANDAL",
                "SEATALLAN",
                "SEATHWAITE_FELL",
                "SELSIDE_PIKE",
                "SERGEANT_MAN",
                "SERGEANTS_CRAG",
                "SHEFFIELD_PIKE",
                "SHIPMAN_KNOTTS",
                "SILVER_HOW",
                "SKIDDAW",
                "SKIDDAW_LITTLE_MAN",
                "SLIGHT_SIDE",
                "SOUR_HOWES",
                "SOUTHER_FELL",
                "ST_SUNDAY_CRAG",
                "STARLING_DODD",
                "STEEL_FELL",
                "STEEL_KNOTTS",
                "STEEPLE",
                "STONE_ARTHUR",
                "CAUDALE_MOOR",
                "STYBARROW_DODD",
                "SWIRL_HOW",
                "TARN_CRAG_EASEDALE",
                "TARN_CRAG_SLEDDALE",
                "THE_KNOTT",
                "THE_NAB",
                "THORNTHWAITE_CRAG",
                "THUNACAR_KNOTT",
                "TROUTBECK_TONGUE",
                "ULLOCK_PIKE",
                "ULLSCARF",
                "WALLA_CRAG",
                "WANDOPE",
                "WANSFELL",
                "WATSONS_DODD",
                "WETHER_HILL",
                "WETHERLAM",
                "WHIN_RIGG",
                "WHINLATTER",
                "WHITE_SIDE",
                "WHITELESS_PIKE",
                "WHITESIDE",
                "YEWBARROW",
                "YOKE",
                name="fellname",
            ),
            nullable=False,
        ),
        sa.Column("display", sa.String(length=50), nullable=False),
        sa.Column("height_rank", sa.Integer(), nullable=False),
        sa.Column("height_m", sa.Integer(), nullable=False),
        sa.Column("os_grid_reference", sa.String(length=8), nullable=False),
        sa.Column(
            "book",
            sa.Enum(
                "EASTERN",
                "FAR_EASTERN",
                "CENTRAL",
                "SOUTHERN",
                "NORTHERN",
                "NORTH_WESTERN",
                "WESTERN",
                name="book",
            ),
            nullable=False,
        ),
        sa.Column("rank_in_book", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("display"),
        sa.UniqueConstraint("height_rank"),
        sa.UniqueConstraint("os_grid_reference"),
    )
    op.create_index(op.f("ix_fell_name"), "fell", ["name"], unique=True)

    # TABLE: user
    op.create_table(
        "user",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column(
            "created_timestamp",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_created_timestamp"),
        "user",
        ["created_timestamp"],
        unique=False,
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(
        op.f("ix_user_username"), "user", ["username"], unique=True
    )
    op.bulk_insert(
        fell,
        [
            {
                "name": "ALLEN_CRAGS",
                "display": "Allen Crags",
                "height_rank": 42,
                "height_m": 785,
                "os_grid_reference": "NY236085",
                "book": "SOUTHERN",
                "rank_in_book": 12,
            },
            {
                "name": "ANGLETARN_PIKES",
                "display": "Angletarn Pikes",
                "height_rank": 143,
                "height_m": 567,
                "os_grid_reference": "NY413148",
                "book": "FAR_EASTERN",
                "rank_in_book": 26,
            },
            {
                "name": "ARD_CRAGS",
                "display": "Ard Crags",
                "height_rank": 136,
                "height_m": 581,
                "os_grid_reference": "NY206197",
                "book": "NORTH_WESTERN",
                "rank_in_book": 16,
            },
            {
                "name": "ARMBOTH_FELL",
                "display": "Armboth Fell",
                "height_rank": 183,
                "height_m": 475,
                "os_grid_reference": "NY295157",
                "book": "CENTRAL",
                "rank_in_book": 18,
            },
            {
                "name": "ARNISON_CRAG",
                "display": "Arnison Crag",
                "height_rank": 194,
                "height_m": 433,
                "os_grid_reference": "NY393149",
                "book": "EASTERN",
                "rank_in_book": 35,
            },
            {
                "name": "ARTHURS_PIKE",
                "display": "Arthur's Pike",
                "height_rank": 157,
                "height_m": 533,
                "os_grid_reference": "NY460206",
                "book": "FAR_EASTERN",
                "rank_in_book": 28,
            },
            {
                "name": "BAKESTALL",
                "display": "Bakestall",
                "height_rank": 100,
                "height_m": 673,
                "os_grid_reference": "NY266308",
                "book": "NORTHERN",
                "rank_in_book": 12,
            },
            {
                "name": "BANNERDALE_CRAGS",
                "display": "Bannerdale Crags",
                "height_rank": 97,
                "height_m": 683,
                "os_grid_reference": "NY335290",
                "book": "NORTHERN",
                "rank_in_book": 11,
            },
            {
                "name": "BARF",
                "display": "Barf",
                "height_rank": 185,
                "height_m": 469,
                "os_grid_reference": "NY214267",
                "book": "NORTH_WESTERN",
                "rank_in_book": 22,
            },
            {
                "name": "BARROW",
                "display": "Barrow",
                "height_rank": 187,
                "height_m": 455,
                "os_grid_reference": "NY227218",
                "book": "NORTH_WESTERN",
                "rank_in_book": 23,
            },
            {
                "name": "BASE_BROWN",
                "display": "Base Brown",
                "height_rank": 117,
                "height_m": 646,
                "os_grid_reference": "NY225114",
                "book": "WESTERN",
                "rank_in_book": 17,
            },
            {
                "name": "BEDA_FELL",
                "display": "Beda Fell (Beda Head)",
                "height_rank": 171,
                "height_m": 509,
                "os_grid_reference": "NY428171",
                "book": "FAR_EASTERN",
                "rank_in_book": 31,
            },
            {
                "name": "BINSEY",
                "display": "Binsey",
                "height_rank": 192,
                "height_m": 447,
                "os_grid_reference": "NY225355",
                "book": "NORTHERN",
                "rank_in_book": 23,
            },
            {
                "name": "BIRKHOUSE_MOOR",
                "display": "Birkhouse Moor",
                "height_rank": 78,
                "height_m": 718,
                "os_grid_reference": "NY363159",
                "book": "EASTERN",
                "rank_in_book": 19,
            },
            {
                "name": "BIRKS",
                "display": "Birks",
                "height_rank": 124,
                "height_m": 622,
                "os_grid_reference": "NY380143",
                "book": "EASTERN",
                "rank_in_book": 24,
            },
            {
                "name": "BLACK_FELL",
                "display": "Black Fell",
                "height_rank": 212,
                "height_m": 323,
                "os_grid_reference": "NY340015",
                "book": "SOUTHERN",
                "rank_in_book": 29,
            },
            {
                "name": "BLAKE_FELL",
                "display": "Blake Fell",
                "height_rank": 140,
                "height_m": 573,
                "os_grid_reference": "NY110196",
                "book": "WESTERN",
                "rank_in_book": 23,
            },
            {
                "name": "BLEA_RIGG",
                "display": "Blea Rigg",
                "height_rank": 152,
                "height_m": 541,
                "os_grid_reference": "NY301078",
                "book": "CENTRAL",
                "rank_in_book": 14,
            },
            {
                "name": "BLEABERRY_FELL",
                "display": "Bleaberry Fell",
                "height_rank": 132,
                "height_m": 590,
                "os_grid_reference": "NY285195",
                "book": "CENTRAL",
                "rank_in_book": 10,
            },
            {
                "name": "BLENCATHRA",
                "display": "Blencathra (Hallsfell Top)",
                "height_rank": 14,
                "height_m": 868,
                "os_grid_reference": "NY323277",
                "book": "NORTHERN",
                "rank_in_book": 2,
            },
            {
                "name": "BONSCALE_PIKE",
                "display": "Bonscale Pike",
                "height_rank": 161,
                "height_m": 524,
                "os_grid_reference": "NY453200",
                "book": "FAR_EASTERN",
                "rank_in_book": 29,
            },
            {
                "name": "BOWFELL",
                "display": "Bowfell",
                "height_rank": 6,
                "height_m": 903,
                "os_grid_reference": "NY244064",
                "book": "SOUTHERN",
                "rank_in_book": 4,
            },
            {
                "name": "BOWSCALE_FELL",
                "display": "Bowscale Fell",
                "height_rank": 87,
                "height_m": 702,
                "os_grid_reference": "NY333305",
                "book": "NORTHERN",
                "rank_in_book": 8,
            },
            {
                "name": "BRAE_FELL",
                "display": "Brae Fell",
                "height_rank": 134,
                "height_m": 586,
                "os_grid_reference": "NY288351",
                "book": "NORTHERN",
                "rank_in_book": 17,
            },
            {
                "name": "BRANDRETH",
                "display": "Brandreth",
                "height_rank": 80,
                "height_m": 715,
                "os_grid_reference": "NY214119",
                "book": "WESTERN",
                "rank_in_book": 12,
            },
            {
                "name": "BRANSTREE",
                "display": "Branstree",
                "height_rank": 81,
                "height_m": 713,
                "os_grid_reference": "NY478099",
                "book": "FAR_EASTERN",
                "rank_in_book": 13,
            },
            {
                "name": "BRIM_FELL",
                "display": "Brim Fell",
                "height_rank": 37,
                "height_m": 796,
                "os_grid_reference": "SD270985",
                "book": "SOUTHERN",
                "rank_in_book": 10,
            },
            {
                "name": "BROCK_CRAGS",
                "display": "Brock Crags",
                "height_rank": 144,
                "height_m": 561,
                "os_grid_reference": "NY416136",
                "book": "FAR_EASTERN",
                "rank_in_book": 27,
            },
            {
                "name": "BROOM_FELL",
                "display": "Broom Fell",
                "height_rank": 169,
                "height_m": 511,
                "os_grid_reference": "NY194271",
                "book": "NORTH_WESTERN",
                "rank_in_book": 21,
            },
            {
                "name": "BUCKBARROW",
                "display": "Buckbarrow",
                "height_rank": 197,
                "height_m": 423,
                "os_grid_reference": "NY135061",
                "book": "WESTERN",
                "rank_in_book": 32,
            },
            {
                "name": "BURNBANK_FELL",
                "display": "Burnbank Fell",
                "height_rank": 182,
                "height_m": 475,
                "os_grid_reference": "NY110209",
                "book": "WESTERN",
                "rank_in_book": 30,
            },
            {
                "name": "CALF_CRAG",
                "display": "Calf Crag",
                "height_rank": 154,
                "height_m": 537,
                "os_grid_reference": "NY301104",
                "book": "CENTRAL",
                "rank_in_book": 15,
            },
            {
                "name": "CARL_SIDE",
                "display": "Carl Side",
                "height_rank": 64,
                "height_m": 746,
                "os_grid_reference": "NY254280",
                "book": "NORTHERN",
                "rank_in_book": 4,
            },
            {
                "name": "CARROCK_FELL",
                "display": "Carrock Fell",
                "height_rank": 105,
                "height_m": 663,
                "os_grid_reference": "NY341336",
                "book": "NORTHERN",
                "rank_in_book": 13,
            },
            {
                "name": "CASTLE_CRAG",
                "display": "Castle Crag",
                "height_rank": 214,
                "height_m": 290,
                "os_grid_reference": "NY249159",
                "book": "NORTH_WESTERN",
                "rank_in_book": 29,
            },
            {
                "name": "CATBELLS",
                "display": "Catbells",
                "height_rank": 189,
                "height_m": 451,
                "os_grid_reference": "NY244198",
                "book": "NORTH_WESTERN",
                "rank_in_book": 25,
            },
            {
                "name": "CATSTYE_CAM",
                "display": "Catstye Cam",
                "height_rank": 10,
                "height_m": 890,
                "os_grid_reference": "NY348158",
                "book": "EASTERN",
                "rank_in_book": 3,
            },
            {
                "name": "CAUDALE_MOOR",
                "display": "Caudale Moore (Stony Cove Pike)",
                "height_rank": 55,
                "height_m": 763,
                "os_grid_reference": "NY417100",
                "book": "FAR_EASTERN",
                "rank_in_book": 7,
            },
            {
                "name": "CAUSEY_PIKE",
                "display": "Causey Pike",
                "height_rank": 119,
                "height_m": 637,
                "os_grid_reference": "NY218208",
                "book": "NORTH_WESTERN",
                "rank_in_book": 14,
            },
            {
                "name": "CAW_FELL",
                "display": "Caw Fell",
                "height_rank": 92,
                "height_m": 697,
                "os_grid_reference": "NY132109",
                "book": "WESTERN",
                "rank_in_book": 13,
            },
            {
                "name": "CLOUGH_HEAD",
                "display": "Clough Head",
                "height_rank": 75,
                "height_m": 726,
                "os_grid_reference": "NY333225",
                "book": "EASTERN",
                "rank_in_book": 18,
            },
            {
                "name": "COLD_PIKE",
                "display": "Cold Pike",
                "height_rank": 88,
                "height_m": 701,
                "os_grid_reference": "NY262036",
                "book": "SOUTHERN",
                "rank_in_book": 19,
            },
            {
                "name": "CONISTON_OLD_MAN",
                "display": "Coniston Old Man",
                "height_rank": 31,
                "height_m": 802,
                "os_grid_reference": "SD272978",
                "book": "SOUTHERN",
                "rank_in_book": 8,
            },
            {
                "name": "CRAG_FELL",
                "display": "Crag Fell",
                "height_rank": 162,
                "height_m": 523,
                "os_grid_reference": "NY097143",
                "book": "WESTERN",
                "rank_in_book": 26,
            },
            {
                "name": "CRINKLE_CRAGS",
                "display": "Crinkle Crags (Long Top)",
                "height_rank": 17,
                "height_m": 859,
                "os_grid_reference": "NY248048",
                "book": "SOUTHERN",
                "rank_in_book": 6,
            },
            {
                "name": "DALE_HEAD",
                "display": "Dale Head",
                "height_rank": 63,
                "height_m": 753,
                "os_grid_reference": "NY222153",
                "book": "NORTH_WESTERN",
                "rank_in_book": 7,
            },
            {
                "name": "DODD",
                "display": "Dodd (Skiddaw)",
                "height_rank": 175,
                "height_m": 502,
                "os_grid_reference": "NY244273",
                "book": "NORTHERN",
                "rank_in_book": 21,
            },
            {
                "name": "DOLLYWAGGON_PIKE",
                "display": "Dollywaggon Pike",
                "height_rank": 18,
                "height_m": 858,
                "os_grid_reference": "NY346130",
                "book": "EASTERN",
                "rank_in_book": 7,
            },
            {
                "name": "DOVE_CRAG",
                "display": "Dove Crag",
                "height_rank": 39,
                "height_m": 792,
                "os_grid_reference": "NY374104",
                "book": "EASTERN",
                "rank_in_book": 12,
            },
            {
                "name": "DOW_CRAG",
                "display": "Dow Crag",
                "height_rank": 48,
                "height_m": 778,
                "os_grid_reference": "SD262977",
                "book": "SOUTHERN",
                "rank_in_book": 14,
            },
            {
                "name": "EAGLE_CRAG",
                "display": "Eagle Crag",
                "height_rank": 160,
                "height_m": 525,
                "os_grid_reference": "NY275121",
                "book": "CENTRAL",
                "rank_in_book": 17,
            },
            {
                "name": "EEL_CRAG",
                "display": "Eel Crag (Crag Hill)",
                "height_rank": 24,
                "height_m": 839,
                "os_grid_reference": "NY192203",
                "book": "NORTH_WESTERN",
                "rank_in_book": 2,
            },
            {
                "name": "ESK_PIKE",
                "display": "Esk Pike",
                "height_rank": 11,
                "height_m": 885,
                "os_grid_reference": "NY236075",
                "book": "SOUTHERN",
                "rank_in_book": 5,
            },
            {
                "name": "FAIRFIELD",
                "display": "Fairfield",
                "height_rank": 13,
                "height_m": 873,
                "os_grid_reference": "NY358117",
                "book": "EASTERN",
                "rank_in_book": 5,
            },
            {
                "name": "FELLBARROW",
                "display": "Fellbarrow (Mosser Fell)",
                "height_rank": 199,
                "height_m": 416,
                "os_grid_reference": "NY132242",
                "book": "WESTERN",
                "rank_in_book": 33,
            },
            {
                "name": "FLEETWITH_PIKE",
                "display": "Fleetwith Pike",
                "height_rank": 116,
                "height_m": 649,
                "os_grid_reference": "NY205141",
                "book": "WESTERN",
                "rank_in_book": 16,
            },
            {
                "name": "FROSWICK",
                "display": "Froswick",
                "height_rank": 77,
                "height_m": 720,
                "os_grid_reference": "NY435085",
                "book": "FAR_EASTERN",
                "rank_in_book": 12,
            },
            {
                "name": "GAVEL_FELL",
                "display": "Gavel Fell",
                "height_rank": 159,
                "height_m": 526,
                "os_grid_reference": "NY116183",
                "book": "WESTERN",
                "rank_in_book": 25,
            },
            {
                "name": "GIBSON_KNOTT",
                "display": "Gibson Knott",
                "height_rank": 198,
                "height_m": 420,
                "os_grid_reference": "NY316100",
                "book": "CENTRAL",
                "rank_in_book": 21,
            },
            {
                "name": "GLARAMARA",
                "display": "Glaramara",
                "height_rank": 45,
                "height_m": 783,
                "os_grid_reference": "NY245104",
                "book": "SOUTHERN",
                "rank_in_book": 13,
            },
            {
                "name": "GLENRIDDING_DODD",
                "display": "Glenridding Dodd",
                "height_rank": 193,
                "height_m": 442,
                "os_grid_reference": "NY380175",
                "book": "EASTERN",
                "rank_in_book": 34,
            },
            {
                "name": "GOWBARROW_FELL",
                "display": "Gowbarrow Fell",
                "height_rank": 181,
                "height_m": 481,
                "os_grid_reference": "NY407218",
                "book": "EASTERN",
                "rank_in_book": 32,
            },
            {
                "name": "GRANGE_FELL",
                "display": "Grange Fell (Brund Fell)",
                "height_rank": 200,
                "height_m": 416,
                "os_grid_reference": "NY264162",
                "book": "CENTRAL",
                "rank_in_book": 22,
            },
            {
                "name": "GRASMOOR",
                "display": "Grasmoor",
                "height_rank": 20,
                "height_m": 852,
                "os_grid_reference": "NY174203",
                "book": "NORTH_WESTERN",
                "rank_in_book": 1,
            },
            {
                "name": "GRAY_CRAG",
                "display": "Gray Crag",
                "height_rank": 90,
                "height_m": 699,
                "os_grid_reference": "NY427117",
                "book": "FAR_EASTERN",
                "rank_in_book": 15,
            },
            {
                "name": "GRAYSTONES",
                "display": "Graystones",
                "height_rank": 188,
                "height_m": 452,
                "os_grid_reference": "NY176266",
                "book": "NORTH_WESTERN",
                "rank_in_book": 24,
            },
            {
                "name": "GREAT_BORNE",
                "display": "Great Borne",
                "height_rank": 126,
                "height_m": 616,
                "os_grid_reference": "NY123163",
                "book": "WESTERN",
                "rank_in_book": 20,
            },
            {
                "name": "GREAT_CALVA",
                "display": "Great Calva",
                "height_rank": 96,
                "height_m": 690,
                "os_grid_reference": "NY290311",
                "book": "NORTHERN",
                "rank_in_book": 9,
            },
            {
                "name": "GREAT_CARRS",
                "display": "Great Carrs",
                "height_rank": 43,
                "height_m": 785,
                "os_grid_reference": "NY270009",
                "book": "SOUTHERN",
                "rank_in_book": 11,
            },
            {
                "name": "GREAT_COCKUP",
                "display": "Great Cockup",
                "height_rank": 158,
                "height_m": 526,
                "os_grid_reference": "NY273333",
                "book": "NORTHERN",
                "rank_in_book": 19,
            },
            {
                "name": "GREAT_CRAG",
                "display": "Great Crag",
                "height_rank": 191,
                "height_m": 449,
                "os_grid_reference": "NY270146",
                "book": "CENTRAL",
                "rank_in_book": 20,
            },
            {
                "name": "GREAT_DODD",
                "display": "Great Dodd",
                "height_rank": 19,
                "height_m": 857,
                "os_grid_reference": "NY342205",
                "book": "EASTERN",
                "rank_in_book": 8,
            },
            {
                "name": "GREAT_END",
                "display": "Great End",
                "height_rank": 5,
                "height_m": 910,
                "os_grid_reference": "NY226083",
                "book": "SOUTHERN",
                "rank_in_book": 3,
            },
            {
                "name": "GREAT_GABLE",
                "display": "Great Gable",
                "height_rank": 7,
                "height_m": 899,
                "os_grid_reference": "NY211103",
                "book": "WESTERN",
                "rank_in_book": 1,
            },
            {
                "name": "GREAT_MELL_FELL",
                "display": "Great Mell Fell",
                "height_rank": 156,
                "height_m": 537,
                "os_grid_reference": "NY396253",
                "book": "EASTERN",
                "rank_in_book": 27,
            },
            {
                "name": "GREAT_RIGG",
                "display": "Great Rigg",
                "height_rank": 54,
                "height_m": 766,
                "os_grid_reference": "NY355104",
                "book": "EASTERN",
                "rank_in_book": 15,
            },
            {
                "name": "GREAT_SCA_FELL",
                "display": "Great Sca Fell",
                "height_rank": 114,
                "height_m": 651,
                "os_grid_reference": "NY291339",
                "book": "NORTHERN",
                "rank_in_book": 15,
            },
            {
                "name": "GREEN_CRAG",
                "display": "Green Crag",
                "height_rank": 176,
                "height_m": 489,
                "os_grid_reference": "SD200982",
                "book": "SOUTHERN",
                "rank_in_book": 27,
            },
            {
                "name": "GREEN_GABLE",
                "display": "Green Gable",
                "height_rank": 35,
                "height_m": 801,
                "os_grid_reference": "NY214107",
                "book": "WESTERN",
                "rank_in_book": 8,
            },
            {
                "name": "GREY_CRAG",
                "display": "Grey Crag (Sleddale)",
                "height_rank": 118,
                "height_m": 638,
                "os_grid_reference": "NY497072",
                "book": "FAR_EASTERN",
                "rank_in_book": 22,
            },
            {
                "name": "GREY_FRIAR",
                "display": "Grey Friar",
                "height_rank": 51,
                "height_m": 773,
                "os_grid_reference": "NY260003",
                "book": "SOUTHERN",
                "rank_in_book": 15,
            },
            {
                "name": "GREY_KNOTTS",
                "display": "Grey Knotts",
                "height_rank": 91,
                "height_m": 697,
                "os_grid_reference": "NY217125",
                "book": "WESTERN",
                "rank_in_book": 14,
            },
            {
                "name": "GRIKE",
                "display": "Grike",
                "height_rank": 177,
                "height_m": 488,
                "os_grid_reference": "NY084140",
                "book": "WESTERN",
                "rank_in_book": 29,
            },
            {
                "name": "GRISEDALE_PIKE",
                "display": "Grisedale Pike",
                "height_rank": 40,
                "height_m": 791,
                "os_grid_reference": "NY198225",
                "book": "NORTH_WESTERN",
                "rank_in_book": 3,
            },
            {
                "name": "HALLIN_FELL",
                "display": "Hallin Fell",
                "height_rank": 203,
                "height_m": 388,
                "os_grid_reference": "NY433198",
                "book": "FAR_EASTERN",
                "rank_in_book": 35,
            },
            {
                "name": "HARD_KNOTT",
                "display": "Hard Knott",
                "height_rank": 151,
                "height_m": 549,
                "os_grid_reference": "NY231023",
                "book": "SOUTHERN",
                "rank_in_book": 25,
            },
            {
                "name": "HARRISON_STICKLE",
                "display": "Harrison Stickle",
                "height_rank": 69,
                "height_m": 736,
                "os_grid_reference": "NY281074",
                "book": "CENTRAL",
                "rank_in_book": 2,
            },
            {
                "name": "HART_CRAG",
                "display": "Hart Crag",
                "height_rank": 27,
                "height_m": 822,
                "os_grid_reference": "NY369112",
                "book": "EASTERN",
                "rank_in_book": 11,
            },
            {
                "name": "HART_SIDE",
                "display": "Hart Side",
                "height_rank": 61,
                "height_m": 756,
                "os_grid_reference": "NY359197",
                "book": "EASTERN",
                "rank_in_book": 16,
            },
            {
                "name": "HARTER_FELL_ESKDALE",
                "display": "Harter Fell (Eskdale)",
                "height_rank": 112,
                "height_m": 654,
                "os_grid_reference": "SD218997",
                "book": "SOUTHERN",
                "rank_in_book": 20,
            },
            {
                "name": "HARTER_FELL_MARDALE",
                "display": "Harter Fell (Mardale)",
                "height_rank": 47,
                "height_m": 779,
                "os_grid_reference": "NY459093",
                "book": "FAR_EASTERN",
                "rank_in_book": 6,
            },
            {
                "name": "HARTSOP_ABOVE_HOW",
                "display": "Hartsop Above How",
                "height_rank": 137,
                "height_m": 581,
                "os_grid_reference": "NY383120",
                "book": "EASTERN",
                "rank_in_book": 26,
            },
            {
                "name": "HARTSOP_DODD",
                "display": "Hartsop Dodd",
                "height_rank": 125,
                "height_m": 618,
                "os_grid_reference": "NY411118",
                "book": "FAR_EASTERN",
                "rank_in_book": 23,
            },
            {
                "name": "HAYCOCK",
                "display": "Haycock",
                "height_rank": 36,
                "height_m": 797,
                "os_grid_reference": "NY144107",
                "book": "WESTERN",
                "rank_in_book": 9,
            },
            {
                "name": "HAYSTACKS",
                "display": "Haystacks (Buttermere)",
                "height_rank": 131,
                "height_m": 597,
                "os_grid_reference": "NY193131",
                "book": "WESTERN",
                "rank_in_book": 21,
            },
            {
                "name": "HELM_CRAG",
                "display": "Helm Crag",
                "height_rank": 201,
                "height_m": 405,
                "os_grid_reference": "NY326093",
                "book": "CENTRAL",
                "rank_in_book": 23,
            },
            {
                "name": "HELVELLYN",
                "display": "Helvellyn",
                "height_rank": 3,
                "height_m": 950,
                "os_grid_reference": "NY342151",
                "book": "EASTERN",
                "rank_in_book": 1,
            },
            {
                "name": "HEN_COMB",
                "display": "Hen Comb",
                "height_rank": 170,
                "height_m": 509,
                "os_grid_reference": "NY132181",
                "book": "WESTERN",
                "rank_in_book": 28,
            },
            {
                "name": "HERON_PIKE",
                "display": "Heron Pike",
                "height_rank": 127,
                "height_m": 612,
                "os_grid_reference": "NY355083",
                "book": "EASTERN",
                "rank_in_book": 25,
            },
            {
                "name": "HIGH_CRAG",
                "display": "High Crag (Buttermere)",
                "height_rank": 65,
                "height_m": 744,
                "os_grid_reference": "NY180139",
                "book": "WESTERN",
                "rank_in_book": 11,
            },
            {
                "name": "HIGH_HARTSOP_DODD",
                "display": "High Hartsop Dodd",
                "height_rank": 164,
                "height_m": 519,
                "os_grid_reference": "NY393107",
                "book": "EASTERN",
                "rank_in_book": 28,
            },
            {
                "name": "HIGH_PIKE_CALDBECK",
                "display": "High Pike (Caldbeck)",
                "height_rank": 107,
                "height_m": 658,
                "os_grid_reference": "NY318350",
                "book": "NORTHERN",
                "rank_in_book": 14,
            },
            {
                "name": "HIGH_PIKE_SCANDALE",
                "display": "High Pike (Scandale)",
                "height_rank": 109,
                "height_m": 656,
                "os_grid_reference": "NY374088",
                "book": "EASTERN",
                "rank_in_book": 21,
            },
            {
                "name": "HIGH_RAISE_HIGH_STREET",
                "display": "High Raise (High Street)",
                "height_rank": 34,
                "height_m": 802,
                "os_grid_reference": "NY448134",
                "book": "FAR_EASTERN",
                "rank_in_book": 2,
            },
            {
                "name": "HIGH_RAISE_LANGDALE",
                "display": "High Raise (Langdale)",
                "height_rank": 57,
                "height_m": 762,
                "os_grid_reference": "NY280095",
                "book": "CENTRAL",
                "rank_in_book": 1,
            },
            {
                "name": "HIGH_RIGG",
                "display": "High Rigg (Naddle Fell)",
                "height_rank": 209,
                "height_m": 357,
                "os_grid_reference": "NY308219",
                "book": "CENTRAL",
                "rank_in_book": 26,
            },
            {
                "name": "HIGH_SEAT",
                "display": "High Seat",
                "height_rank": 129,
                "height_m": 608,
                "os_grid_reference": "NY287180",
                "book": "CENTRAL",
                "rank_in_book": 9,
            },
            {
                "name": "HIGH_SPY",
                "display": "High Spy",
                "height_rank": 113,
                "height_m": 653,
                "os_grid_reference": "NY234162",
                "book": "NORTH_WESTERN",
                "rank_in_book": 13,
            },
            {
                "name": "HIGH_STILE",
                "display": "High Stile",
                "height_rank": 30,
                "height_m": 806,
                "os_grid_reference": "NY167147",
                "book": "WESTERN",
                "rank_in_book": 6,
            },
            {
                "name": "HIGH_STREET",
                "display": "High Street",
                "height_rank": 25,
                "height_m": 828,
                "os_grid_reference": "NY440110",
                "book": "FAR_EASTERN",
                "rank_in_book": 1,
            },
            {
                "name": "HIGH_TOVE",
                "display": "High Tove",
                "height_rank": 167,
                "height_m": 515,
                "os_grid_reference": "NY289165",
                "book": "CENTRAL",
                "rank_in_book": 16,
            },
            {
                "name": "HINDSCARTH",
                "display": "Hindscarth",
                "height_rank": 73,
                "height_m": 727,
                "os_grid_reference": "NY215165",
                "book": "NORTH_WESTERN",
                "rank_in_book": 9,
            },
            {
                "name": "HOLME_FELL",
                "display": "Holme Fell",
                "height_rank": 213,
                "height_m": 317,
                "os_grid_reference": "NY315006",
                "book": "SOUTHERN",
                "rank_in_book": 30,
            },
            {
                "name": "HOPEGILL_HEAD",
                "display": "Hopegill Head",
                "height_rank": 53,
                "height_m": 770,
                "os_grid_reference": "NY185221",
                "book": "NORTH_WESTERN",
                "rank_in_book": 6,
            },
            {
                "name": "ILL_BELL",
                "display": "Ill Bell",
                "height_rank": 60,
                "height_m": 757,
                "os_grid_reference": "NY436077",
                "book": "FAR_EASTERN",
                "rank_in_book": 9,
            },
            {
                "name": "ILLGILL_HEAD",
                "display": "Illgill Head",
                "height_rank": 128,
                "height_m": 609,
                "os_grid_reference": "NY168049",
                "book": "SOUTHERN",
                "rank_in_book": 22,
            },
            {
                "name": "KENTMERE_PIKE",
                "display": "Kentmere Pike",
                "height_rank": 72,
                "height_m": 730,
                "os_grid_reference": "NY465077",
                "book": "FAR_EASTERN",
                "rank_in_book": 11,
            },
            {
                "name": "KIDSTY_PIKE",
                "display": "Kidsty Pike",
                "height_rank": 46,
                "height_m": 780,
                "os_grid_reference": "NY447125",
                "book": "FAR_EASTERN",
                "rank_in_book": 5,
            },
            {
                "name": "KIRK_FELL",
                "display": "Kirk Fell",
                "height_rank": 33,
                "height_m": 802,
                "os_grid_reference": "NY194104",
                "book": "WESTERN",
                "rank_in_book": 7,
            },
            {
                "name": "KNOTT",
                "display": "Knott",
                "height_rank": 82,
                "height_m": 710,
                "os_grid_reference": "NY296329",
                "book": "NORTHERN",
                "rank_in_book": 7,
            },
            {
                "name": "KNOTT_RIGG",
                "display": "Knott Rigg",
                "height_rank": 145,
                "height_m": 556,
                "os_grid_reference": "NY197188",
                "book": "NORTH_WESTERN",
                "rank_in_book": 18,
            },
            {
                "name": "LANK_RIGG",
                "display": "Lank Rigg",
                "height_rank": 153,
                "height_m": 541,
                "os_grid_reference": "NY091119",
                "book": "WESTERN",
                "rank_in_book": 24,
            },
            {
                "name": "LATRIGG",
                "display": "Latrigg",
                "height_rank": 206,
                "height_m": 368,
                "os_grid_reference": "NY279247",
                "book": "NORTHERN",
                "rank_in_book": 24,
            },
            {
                "name": "LING_FELL",
                "display": "Ling Fell",
                "height_rank": 205,
                "height_m": 373,
                "os_grid_reference": "NY179285",
                "book": "NORTH_WESTERN",
                "rank_in_book": 26,
            },
            {
                "name": "LINGMELL",
                "display": "Lingmell",
                "height_rank": 29,
                "height_m": 807,
                "os_grid_reference": "NY209081",
                "book": "SOUTHERN",
                "rank_in_book": 7,
            },
            {
                "name": "LINGMOOR_FELL",
                "display": "Lingmoor Fell",
                "height_rank": 184,
                "height_m": 470,
                "os_grid_reference": "NY302046",
                "book": "SOUTHERN",
                "rank_in_book": 28,
            },
            {
                "name": "LITTLE_HART_CRAG",
                "display": "Little Hart Crag",
                "height_rank": 120,
                "height_m": 637,
                "os_grid_reference": "NY387100",
                "book": "EASTERN",
                "rank_in_book": 23,
            },
            {
                "name": "LITTLE_MELL_FELL",
                "display": "Little Mell Fell",
                "height_rank": 173,
                "height_m": 505,
                "os_grid_reference": "NY423240",
                "book": "EASTERN",
                "rank_in_book": 30,
            },
            {
                "name": "LOADPOT_HILL",
                "display": "Loadpot Hill",
                "height_rank": 102,
                "height_m": 672,
                "os_grid_reference": "NY456180",
                "book": "FAR_EASTERN",
                "rank_in_book": 17,
            },
            {
                "name": "LOFT_CRAG",
                "display": "Loft Crag",
                "height_rank": 98,
                "height_m": 680,
                "os_grid_reference": "NY277071",
                "book": "CENTRAL",
                "rank_in_book": 8,
            },
            {
                "name": "LONG_SIDE",
                "display": "Long Side",
                "height_rank": 71,
                "height_m": 734,
                "os_grid_reference": "NY248284",
                "book": "NORTHERN",
                "rank_in_book": 5,
            },
            {
                "name": "LONGLANDS_FELL",
                "display": "Longlands Fell",
                "height_rank": 179,
                "height_m": 483,
                "os_grid_reference": "NY275354",
                "book": "NORTHERN",
                "rank_in_book": 22,
            },
            {
                "name": "LONSCALE_FELL",
                "display": "Lonscale Fell",
                "height_rank": 79,
                "height_m": 715,
                "os_grid_reference": "NY285271",
                "book": "NORTHERN",
                "rank_in_book": 6,
            },
            {
                "name": "LORDS_SEAT",
                "display": "Lord's Seat",
                "height_rank": 147,
                "height_m": 552,
                "os_grid_reference": "NY204265",
                "book": "NORTH_WESTERN",
                "rank_in_book": 19,
            },
            {
                "name": "LOUGHRIGG_FELL",
                "display": "Loughrigg Fell",
                "height_rank": 211,
                "height_m": 335,
                "os_grid_reference": "NY346051",
                "book": "CENTRAL",
                "rank_in_book": 27,
            },
            {
                "name": "LOW_FELL",
                "display": "Low Fell",
                "height_rank": 196,
                "height_m": 423,
                "os_grid_reference": "NY137226",
                "book": "WESTERN",
                "rank_in_book": 31,
            },
            {
                "name": "LOW_PIKE",
                "display": "Low Pike",
                "height_rank": 172,
                "height_m": 508,
                "os_grid_reference": "NY373078",
                "book": "EASTERN",
                "rank_in_book": 29,
            },
            {
                "name": "MAIDEN_MOOR",
                "display": "Maiden Moor",
                "height_rank": 139,
                "height_m": 575,
                "os_grid_reference": "NY236181",
                "book": "NORTH_WESTERN",
                "rank_in_book": 15,
            },
            {
                "name": "MARDALE_ILL_BELL",
                "display": "Mardale Ill Bell",
                "height_rank": 59,
                "height_m": 760,
                "os_grid_reference": "NY447101",
                "book": "FAR_EASTERN",
                "rank_in_book": 8,
            },
            {
                "name": "MEAL_FELL",
                "display": "Meal Fell",
                "height_rank": 149,
                "height_m": 550,
                "os_grid_reference": "NY283337",
                "book": "NORTHERN",
                "rank_in_book": 18,
            },
            {
                "name": "MELLBREAK",
                "display": "Mellbreak",
                "height_rank": 168,
                "height_m": 512,
                "os_grid_reference": "NY148186",
                "book": "WESTERN",
                "rank_in_book": 27,
            },
            {
                "name": "MIDDLE_DODD",
                "display": "Middle Dodd",
                "height_rank": 111,
                "height_m": 654,
                "os_grid_reference": "NY397095",
                "book": "EASTERN",
                "rank_in_book": 22,
            },
            {
                "name": "MIDDLE_FELL",
                "display": "Middle Fell",
                "height_rank": 135,
                "height_m": 582,
                "os_grid_reference": "NY150072",
                "book": "WESTERN",
                "rank_in_book": 22,
            },
            {
                "name": "MUNGRISDALE_COMMON",
                "display": "Mungrisdale Common",
                "height_rank": 122,
                "height_m": 633,
                "os_grid_reference": "NY310292",
                "book": "NORTHERN",
                "rank_in_book": 16,
            },
            {
                "name": "NAB_SCAR",
                "display": "Nab Scar",
                "height_rank": 190,
                "height_m": 450,
                "os_grid_reference": "NY355072",
                "book": "EASTERN",
                "rank_in_book": 33,
            },
            {
                "name": "NETHERMOST_PIKE",
                "display": "Nethermost Pike",
                "height_rank": 9,
                "height_m": 891,
                "os_grid_reference": "NY343142",
                "book": "EASTERN",
                "rank_in_book": 2,
            },
            {
                "name": "OUTERSIDE",
                "display": "Outerside",
                "height_rank": 142,
                "height_m": 568,
                "os_grid_reference": "NY211214",
                "book": "NORTH_WESTERN",
                "rank_in_book": 17,
            },
            {
                "name": "PAVEY_ARK",
                "display": "Pavey Ark",
                "height_rank": 89,
                "height_m": 700,
                "os_grid_reference": "NY284079",
                "book": "CENTRAL",
                "rank_in_book": 7,
            },
            {
                "name": "PIKE_OF_BLISCO",
                "display": "Pike o' Blisco",
                "height_rank": 86,
                "height_m": 705,
                "os_grid_reference": "NY271042",
                "book": "SOUTHERN",
                "rank_in_book": 18,
            },
            {
                "name": "PIKE_OF_STICKLE",
                "display": "Pike of Stickle",
                "height_rank": 83,
                "height_m": 709,
                "os_grid_reference": "NY273073",
                "book": "CENTRAL",
                "rank_in_book": 6,
            },
            {
                "name": "PILLAR",
                "display": "Pillar",
                "height_rank": 8,
                "height_m": 892,
                "os_grid_reference": "NY171121",
                "book": "WESTERN",
                "rank_in_book": 2,
            },
            {
                "name": "PLACE_FELL",
                "display": "Place Fell",
                "height_rank": 108,
                "height_m": 657,
                "os_grid_reference": "NY405169",
                "book": "FAR_EASTERN",
                "rank_in_book": 20,
            },
            {
                "name": "RAISE",
                "display": "Raise",
                "height_rank": 12,
                "height_m": 883,
                "os_grid_reference": "NY342174",
                "book": "EASTERN",
                "rank_in_book": 4,
            },
            {
                "name": "RAMPSGILL_HEAD",
                "display": "Rampsgill Head",
                "height_rank": 38,
                "height_m": 792,
                "os_grid_reference": "NY443128",
                "book": "FAR_EASTERN",
                "rank_in_book": 3,
            },
            {
                "name": "RANNERDALE_KNOTTS",
                "display": "Rannerdale Knotts",
                "height_rank": 210,
                "height_m": 355,
                "os_grid_reference": "NY167182",
                "book": "NORTH_WESTERN",
                "rank_in_book": 28,
            },
            {
                "name": "RAVEN_CRAG",
                "display": "Raven Crag",
                "height_rank": 186,
                "height_m": 461,
                "os_grid_reference": "NY303187",
                "book": "CENTRAL",
                "rank_in_book": 19,
            },
            {
                "name": "RED_PIKE_BUTTERMERE",
                "display": "Red Pike (Buttermere)",
                "height_rank": 62,
                "height_m": 755,
                "os_grid_reference": "NY160154",
                "book": "WESTERN",
                "rank_in_book": 10,
            },
            {
                "name": "RED_PIKE_WASDALE",
                "display": "Red Pike (Wasdale)",
                "height_rank": 26,
                "height_m": 826,
                "os_grid_reference": "NY165106",
                "book": "WESTERN",
                "rank_in_book": 4,
            },
            {
                "name": "RED_SCREES",
                "display": "Red Screes",
                "height_rank": 49,
                "height_m": 776,
                "os_grid_reference": "NY396087",
                "book": "EASTERN",
                "rank_in_book": 14,
            },
            {
                "name": "REST_DODD",
                "display": "Rest Dodd",
                "height_rank": 93,
                "height_m": 696,
                "os_grid_reference": "NY432136",
                "book": "FAR_EASTERN",
                "rank_in_book": 16,
            },
            {
                "name": "ROBINSON",
                "display": "Robinson",
                "height_rank": 67,
                "height_m": 737,
                "os_grid_reference": "NY201168",
                "book": "NORTH_WESTERN",
                "rank_in_book": 8,
            },
            {
                "name": "ROSSETT_PIKE",
                "display": "Rossett Pike",
                "height_rank": 115,
                "height_m": 651,
                "os_grid_reference": "NY249075",
                "book": "SOUTHERN",
                "rank_in_book": 21,
            },
            {
                "name": "ROSTHWAITE_FELL",
                "display": "Rosthwaite Fell",
                "height_rank": 148,
                "height_m": 551,
                "os_grid_reference": "NY258124",
                "book": "SOUTHERN",
                "rank_in_book": 24,
            },
            {
                "name": "SAIL",
                "display": "Sail",
                "height_rank": 50,
                "height_m": 773,
                "os_grid_reference": "NY198202",
                "book": "NORTH_WESTERN",
                "rank_in_book": 4,
            },
            {
                "name": "SALE_FELL",
                "display": "Sale Fell",
                "height_rank": 208,
                "height_m": 359,
                "os_grid_reference": "NY194296",
                "book": "NORTH_WESTERN",
                "rank_in_book": 27,
            },
            {
                "name": "SALLOWS",
                "display": "Sallows",
                "height_rank": 166,
                "height_m": 516,
                "os_grid_reference": "NY436039",
                "book": "FAR_EASTERN",
                "rank_in_book": 30,
            },
            {
                "name": "SCAFELL",
                "display": "Scafell",
                "height_rank": 2,
                "height_m": 964,
                "os_grid_reference": "NY206064",
                "book": "SOUTHERN",
                "rank_in_book": 2,
            },
            {
                "name": "SCAFELL_PIKE",
                "display": "Scafell Pike",
                "height_rank": 1,
                "height_m": 978,
                "os_grid_reference": "NY215072",
                "book": "SOUTHERN",
                "rank_in_book": 1,
            },
            {
                "name": "SCAR_CRAGS",
                "display": "Scar Crags",
                "height_rank": 101,
                "height_m": 672,
                "os_grid_reference": "NY208206",
                "book": "NORTH_WESTERN",
                "rank_in_book": 11,
            },
            {
                "name": "SCOAT_FELL",
                "display": "Scoat Fell",
                "height_rank": 22,
                "height_m": 841,
                "os_grid_reference": "NY159113",
                "book": "WESTERN",
                "rank_in_book": 3,
            },
            {
                "name": "SEAT_SANDAL",
                "display": "Seat Sandal",
                "height_rank": 68,
                "height_m": 737,
                "os_grid_reference": "NY344115",
                "book": "EASTERN",
                "rank_in_book": 17,
            },
            {
                "name": "SEATALLAN",
                "display": "Seatallan",
                "height_rank": 94,
                "height_m": 692,
                "os_grid_reference": "NY140084",
                "book": "WESTERN",
                "rank_in_book": 15,
            },
            {
                "name": "SEATHWAITE_FELL",
                "display": "Seathwaite Fell",
                "height_rank": 130,
                "height_m": 601,
                "os_grid_reference": "NY229101",
                "book": "SOUTHERN",
                "rank_in_book": 23,
            },
            {
                "name": "SELSIDE_PIKE",
                "display": "Selside Pike",
                "height_rank": 110,
                "height_m": 655,
                "os_grid_reference": "NY490111",
                "book": "FAR_EASTERN",
                "rank_in_book": 21,
            },
            {
                "name": "SERGEANT_MAN",
                "display": "Sergeant Man",
                "height_rank": 70,
                "height_m": 736,
                "os_grid_reference": "NY286088",
                "book": "CENTRAL",
                "rank_in_book": 3,
            },
            {
                "name": "SERGEANTS_CRAG",
                "display": "Sergeant's Crag",
                "height_rank": 141,
                "height_m": 571,
                "os_grid_reference": "NY273113",
                "book": "CENTRAL",
                "rank_in_book": 11,
            },
            {
                "name": "SHEFFIELD_PIKE",
                "display": "Sheffield Pike",
                "height_rank": 99,
                "height_m": 675,
                "os_grid_reference": "NY369181",
                "book": "EASTERN",
                "rank_in_book": 20,
            },
            {
                "name": "SHIPMAN_KNOTTS",
                "display": "Shipman Knotts",
                "height_rank": 133,
                "height_m": 587,
                "os_grid_reference": "NY472062",
                "book": "FAR_EASTERN",
                "rank_in_book": 24,
            },
            {
                "name": "SILVER_HOW",
                "display": "Silver How",
                "height_rank": 202,
                "height_m": 395,
                "os_grid_reference": "NY324066",
                "book": "CENTRAL",
                "rank_in_book": 24,
            },
            {
                "name": "SKIDDAW",
                "display": "Skiddaw",
                "height_rank": 4,
                "height_m": 931,
                "os_grid_reference": "NY260290",
                "book": "NORTHERN",
                "rank_in_book": 1,
            },
            {
                "name": "SKIDDAW_LITTLE_MAN",
                "display": "Skiddaw Little Man",
                "height_rank": 15,
                "height_m": 865,
                "os_grid_reference": "NY266277",
                "book": "NORTHERN",
                "rank_in_book": 3,
            },
            {
                "name": "SLIGHT_SIDE",
                "display": "Slight Side",
                "height_rank": 58,
                "height_m": 762,
                "os_grid_reference": "NY209050",
                "book": "SOUTHERN",
                "rank_in_book": 17,
            },
            {
                "name": "SOUR_HOWES",
                "display": "Sour Howes",
                "height_rank": 180,
                "height_m": 483,
                "os_grid_reference": "NY427032",
                "book": "FAR_EASTERN",
                "rank_in_book": 33,
            },
            {
                "name": "SOUTHER_FELL",
                "display": "Souther Fell",
                "height_rank": 163,
                "height_m": 522,
                "os_grid_reference": "NY354291",
                "book": "NORTHERN",
                "rank_in_book": 20,
            },
            {
                "name": "ST_SUNDAY_CRAG",
                "display": "St Sunday Crag",
                "height_rank": 23,
                "height_m": 841,
                "os_grid_reference": "NY369133",
                "book": "EASTERN",
                "rank_in_book": 10,
            },
            {
                "name": "STARLING_DODD",
                "display": "Starling Dodd",
                "height_rank": 121,
                "height_m": 633,
                "os_grid_reference": "NY142157",
                "book": "WESTERN",
                "rank_in_book": 18,
            },
            {
                "name": "STEEL_FELL",
                "display": "Steel Fell (Dead Pike)",
                "height_rank": 146,
                "height_m": 553,
                "os_grid_reference": "NY319111",
                "book": "CENTRAL",
                "rank_in_book": 12,
            },
            {
                "name": "STEEL_KNOTTS",
                "display": "Steel Knotts",
                "height_rank": 195,
                "height_m": 432,
                "os_grid_reference": "NY440181",
                "book": "FAR_EASTERN",
                "rank_in_book": 34,
            },
            {
                "name": "STEEPLE",
                "display": "Steeple",
                "height_rank": 28,
                "height_m": 819,
                "os_grid_reference": "NY157116",
                "book": "WESTERN",
                "rank_in_book": 5,
            },
            {
                "name": "STONE_ARTHUR",
                "display": "Stone Arthur",
                "height_rank": 174,
                "height_m": 504,
                "os_grid_reference": "NY347092",
                "book": "EASTERN",
                "rank_in_book": 31,
            },
            {
                "name": "STYBARROW_DODD",
                "display": "Stybarrow Dodd",
                "height_rank": 21,
                "height_m": 843,
                "os_grid_reference": "NY343189",
                "book": "EASTERN",
                "rank_in_book": 9,
            },
            {
                "name": "SWIRL_HOW",
                "display": "Swirl How",
                "height_rank": 32,
                "height_m": 802,
                "os_grid_reference": "NY272005",
                "book": "SOUTHERN",
                "rank_in_book": 9,
            },
            {
                "name": "TARN_CRAG_EASEDALE",
                "display": "Tarn Crag (Easedale)",
                "height_rank": 150,
                "height_m": 549,
                "os_grid_reference": "NY303093",
                "book": "CENTRAL",
                "rank_in_book": 13,
            },
            {
                "name": "TARN_CRAG_SLEDDALE",
                "display": "Tarn Crag (Sleddale)",
                "height_rank": 104,
                "height_m": 664,
                "os_grid_reference": "NY488078",
                "book": "FAR_EASTERN",
                "rank_in_book": 19,
            },
            {
                "name": "THE_KNOTT",
                "display": "The Knott (High Street)",
                "height_rank": 66,
                "height_m": 739,
                "os_grid_reference": "NY437126",
                "book": "FAR_EASTERN",
                "rank_in_book": 10,
            },
            {
                "name": "THE_NAB",
                "display": "The Nab",
                "height_rank": 138,
                "height_m": 576,
                "os_grid_reference": "NY434151",
                "book": "FAR_EASTERN",
                "rank_in_book": 25,
            },
            {
                "name": "THORNTHWAITE_CRAG",
                "display": "Thornthwaite Crag",
                "height_rank": 44,
                "height_m": 784,
                "os_grid_reference": "NY431100",
                "book": "FAR_EASTERN",
                "rank_in_book": 4,
            },
            {
                "name": "THUNACAR_KNOTT",
                "display": "Thunacar Knott",
                "height_rank": 76,
                "height_m": 723,
                "os_grid_reference": "NY279079",
                "book": "CENTRAL",
                "rank_in_book": 5,
            },
            {
                "name": "TROUTBECK_TONGUE",
                "display": "Troutbeck Tongue",
                "height_rank": 207,
                "height_m": 364,
                "os_grid_reference": "NY422064",
                "book": "FAR_EASTERN",
                "rank_in_book": 36,
            },
            {
                "name": "ULLOCK_PIKE",
                "display": "Ullock Pike",
                "height_rank": 95,
                "height_m": 690,
                "os_grid_reference": "NY244287",
                "book": "NORTHERN",
                "rank_in_book": 10,
            },
            {
                "name": "ULLSCARF",
                "display": "Ullscarf",
                "height_rank": 74,
                "height_m": 726,
                "os_grid_reference": "NY291121",
                "book": "CENTRAL",
                "rank_in_book": 4,
            },
            {
                "name": "WALLA_CRAG",
                "display": "Walla Crag",
                "height_rank": 204,
                "height_m": 379,
                "os_grid_reference": "NY276212",
                "book": "CENTRAL",
                "rank_in_book": 25,
            },
            {
                "name": "WANDOPE",
                "display": "Wandope",
                "height_rank": 52,
                "height_m": 772,
                "os_grid_reference": "NY188197",
                "book": "NORTH_WESTERN",
                "rank_in_book": 5,
            },
            {
                "name": "WANSFELL",
                "display": "Wansfell (Baystones)",
                "height_rank": 178,
                "height_m": 487,
                "os_grid_reference": "NY403051",
                "book": "FAR_EASTERN",
                "rank_in_book": 32,
            },
            {
                "name": "WATSONS_DODD",
                "display": "Watson's Dodd",
                "height_rank": 41,
                "height_m": 789,
                "os_grid_reference": "NY335195",
                "book": "EASTERN",
                "rank_in_book": 13,
            },
            {
                "name": "WETHER_HILL",
                "display": "Wether Hill",
                "height_rank": 103,
                "height_m": 671,
                "os_grid_reference": "NY455167",
                "book": "FAR_EASTERN",
                "rank_in_book": 18,
            },
            {
                "name": "WETHERLAM",
                "display": "Wetherlam",
                "height_rank": 56,
                "height_m": 763,
                "os_grid_reference": "NY288011",
                "book": "SOUTHERN",
                "rank_in_book": 16,
            },
            {
                "name": "WHIN_RIGG",
                "display": "Whin Rigg",
                "height_rank": 155,
                "height_m": 537,
                "os_grid_reference": "NY151035",
                "book": "SOUTHERN",
                "rank_in_book": 26,
            },
            {
                "name": "WHINLATTER",
                "display": "Whinlatter (Brown How)",
                "height_rank": 165,
                "height_m": 517,
                "os_grid_reference": "NY191251",
                "book": "NORTH_WESTERN",
                "rank_in_book": 20,
            },
            {
                "name": "WHITE_SIDE",
                "display": "White Side",
                "height_rank": 16,
                "height_m": 863,
                "os_grid_reference": "NY337166",
                "book": "EASTERN",
                "rank_in_book": 6,
            },
            {
                "name": "WHITELESS_PIKE",
                "display": "Whiteless Pike",
                "height_rank": 106,
                "height_m": 660,
                "os_grid_reference": "NY180189",
                "book": "NORTH_WESTERN",
                "rank_in_book": 12,
            },
            {
                "name": "WHITESIDE",
                "display": "Whiteside (West Top)",
                "height_rank": 84,
                "height_m": 707,
                "os_grid_reference": "NY170219",
                "book": "NORTH_WESTERN",
                "rank_in_book": 10,
            },
            {
                "name": "YEWBARROW",
                "display": "Yewbarrow",
                "height_rank": 123,
                "height_m": 627,
                "os_grid_reference": "NY173084",
                "book": "WESTERN",
                "rank_in_book": 19,
            },
            {
                "name": "YOKE",
                "display": "Yoke",
                "height_rank": 85,
                "height_m": 706,
                "os_grid_reference": "NY437067",
                "book": "FAR_EASTERN",
                "rank_in_book": 14,
            },
        ],
    )

    # TABLE: summit_event
    op.create_table(
        "summit_event",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("fell_id", sa.UUID(), nullable=False),
        sa.Column("summit_date", sa.Date(), nullable=False),
        sa.Column(
            "created_timestamp",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["fell_id"],
            ["fell.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "fell_id"),
    )
    op.create_index(
        op.f("ix_summit_event_created_timestamp"),
        "summit_event",
        ["created_timestamp"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        op.f("ix_summit_event_created_timestamp"), table_name="summit_event"
    )
    op.drop_table("summit_event")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_index(op.f("ix_user_created_timestamp"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_fell_name"), table_name="fell")
    op.drop_table("fell")
